### ISSUE TITLE
Build UI

### ISSUE THREAD

**Issue by kev007** [IIDP/OSTMap#1]
**Task:** Build the first front-end prototype!
**Assignees:** @kev007 and @ChrizZz110 (@IIDP2016/front-end)
**Deadline:** Meeting 27.04.2016 @ 13:00

**Description:**
1. See attached image
2. 
3. 

![image](https://cloud.githubusercontent.com/assets/3058438/14744074/67e62a4c-08a5-11e6-9874-4c7510edbee7.png)

**Comment by martingrimmer** [comment]
![img_20160422_140034](https://cloud.githubusercontent.com/assets/17045229/14741950/f225f90a-0899-11e6-9ff4-51a18f818f5c.jpg)
