### ISSUE TITLE
Rest service for map search

### ISSUE THREAD

**Issue by martingrimmer** [IIDP/OSTMap#10]
### Goal:

Develop a rest service the OSTMap UI can query against for map search. 
- use spring boot
- path: `/geotemporalsearch`
- parameter:
  - `bbnorth`, `bbsouth`, `bbwest`, `bbeast` the bounding box to search in (given in lat/long)
  - `tstart`, `tend` the time range to search in (given in seconds since 1970)
- returns matching json string, one per line
### Details:

When called the service builds up a connection to accumulo, queries the TermIndex table and than the RawTwitterData with a BatchScanner.

**Comment by ChrizZz110** [comment]
Closed. Next steps for the webservice in a seperate ticket.
