### ISSUE TITLE
UI filename case wrong

### ISSUE THREAD

**Issue by martingrimmer** [IIDP/OSTMap#15]
### Bug Details:

While trying to view the current state of the UI I got two 404 error:
- `"GET /views/mapView.html HTTP/1.1" 404`
- `"GET /views/listView.html HTTP/1.1" 404`
- both seem to be in false case: `/views/MapView.html` and `/views/ListView.html`

**Comment by ChrizZz110** [comment]
I changed the name of both files within GitHub. I will test functionality this evening.

**Comment by merando** [comment]
just take the issue then @ChrizZz110 :)
