### ISSUE TITLE
Unit test  for tokenizer

### ISSUE THREAD

**Issue by martingrimmer** [IIDP/OSTMap#16]
### Goal
- since the tokenizer is a base component for the system we need to trust this component
- therefore we need unit tests for it
### Details
- define a test
  - include the special rules for hashtags and user and the min. 2 sign rule (see [data-schema](https://github.com/IIDP/OSTMap/wiki/Accumulo-schema))
- write a unit test
- this ticket and #4 is done when the test passes and the code is commited

**Comment by CSchott** [comment]
Two different Unit tests are currently created for tokenizer. 
Should both remain?
One created by @HansPog the other by me

**Comment by martingrimmer** [comment]
careful merge of the tokenizer branch into master
