### ISSUE TITLE
transformation old data to new index

### ISSUE THREAD

**Issue by MrBlaTi** [IIDP/OSTMap#2]
### Goal:

Build a flink job which reads all "old" data from the RawTwitterData table and writes the corresponding TermIndex entries.
### Details:
- use the flink dataset api
- see [example](https://github.com/IIDP2016/OSTMap/tree/master/examples/dataset-api-example) how to read data from accumulo using the dataset api
- write data to accumulo using the [AccumuloOutputFormat](https://accumulo.apache.org/1.7/apidocs/org/apache/accumulo/core/client/mapred/AccumuloOutputFormat.html) and the [HadoopOutputFormat](https://ci.apache.org/projects/flink/flink-docs-release-1.0/apis/batch/hadoop_compatibility.html) and [Dataset.output](https://ci.apache.org/projects/flink/flink-docs-release-1.0/api/java/org/apache/flink/api/java/DataSet.html#output%28org.apache.flink.api.common.io.OutputFormat%29)
- see [accumulo-schema](https://github.com/IIDP2016/OSTMap/wiki/Accumulo-schema)

**Comment by martingrimmer** [comment]
![img_20160422_134650](https://cloud.githubusercontent.com/assets/17045229/14741990/275c25fe-089a-11e6-9190-faaa6d1933c3.jpg)

**Comment by martingrimmer** [comment]
see https://github.com/IIDP2016/OSTMap/wiki/Accumulo-schema

**Comment by MrBlaTi** [comment]
save username and screenname both as user
remove number of appearances when number of appearances is 0
