### ISSUE TITLE
Connect webservice to accumulo

### ISSUE THREAD

**Issue by ChrizZz110** [IIDP/OSTMap#20]
At the moment the webservice reads its data from a local json file. The next step is the connection to accumulo.

If a request arrives, the webservice should parse the request, query the database, transform the result into json and give the result back to the requester.

**Comment by CSchott** [comment]
I've got a question concerning the different formats of the geographical coordinates. We discussed in the last meeting, that we should prioritize the formats. Which priority should we use for the geolocations of the rest service?

**Comment by martingrimmer** [comment]
#34

CSchott notifications@github.com schrieb am Di., 10. Mai 2016, 14:44:

**Comment by HansPog** [comment]
Controllers for TokenSearch and GeoTimePeriod should be working (on branch to this issue).

atm there is no option to run GeoTimePeriod search without coordinate window (search only for time).
is this ok, or should there be such an option?

**Comment by martingrimmer** [comment]
at the moment this is ok
