### ISSUE TITLE
tokenizer not working properly with strings containing "..."

### ISSUE THREAD

**Issue by HansPog** [IIDP/OSTMap#21]
currently the tokenizer creates en empty token if a string contains "...". this is probably not intended...
f.eg.: 
`aTokenizer.tokenizeString("hello example ...")
=>{"hello", "example", ""}`

**Comment by CSchott** [comment]
Should already be fixed in upcoming patch

**Comment by MrBlaTi** [comment]
the tokenizer also creates tokens 1 character long. Is this fixed as well in the next patch?

**Comment by CSchott** [comment]
Yes, as mentioned in Issue #4. The new tokenizer should eliminate Strings shorter than 2 and should replace all separators within a given String e.g.: "..." or "!!!" etc. 
Should be ready in a few hours.

**Comment by CSchott** [comment]
New Tokenizer on master branch
