### ISSUE TITLE
[branch: indexingNewData] AccumuloSink

### ISSUE THREAD

**Issue by martingrimmer** [IIDP/OSTMap#24]
- The AccumuloSink does not work propably.
  - configure is called 2 times
  - remove the one with 3 parameter

**Comment by loewenzahm** [comment]
took it because i'm working on the sink(s) anyway

**Comment by loewenzahm** [comment]
took it because i'm working on the sink(s) anyway

**Comment by loewenzahm** [comment]
Created SinkConfiguration class that is why the configure method of the two sinks have been changed.
