### ISSUE TITLE
Indexing new data from Stream

### ISSUE THREAD

**Issue by CSchott** [IIDP/OSTMap#3]
### Goal:

Modify the current running flink stream job to write its data into the RawTwitterData table and the TermIndex table.
### Details:
- use the flink stream api
- see [example](https://github.com/IIDP2016/OSTMap/tree/master/examples/twitter-stream-persist) for reading twitter data and writing to accumulo
- see [accumulo-schema](https://github.com/IIDP2016/OSTMap/wiki/Accumulo-schema)

**Comment by martingrimmer** [comment]
see #2 for index details

**Comment by martingrimmer** [comment]
see https://github.com/IIDP2016/OSTMap/wiki/Accumulo-schema

**Comment by loewenzahm** [comment]
Cannot be pushed because of problems concerning project-structure.

**Comment by martingrimmer** [comment]
If there are problems don't close this ticket. Fix the problems and close it or open a new ticket to fix the problems.

**Comment by loewenzahm** [comment]
Done respectively contained in   #24  #28  #31 #32
