### ISSUE TITLE
Connect GUI with the REST service

### ISSUE THREAD

**Issue by kev007** [IIDP/OSTMap#30]
**Task:** GUI - REST data exchange
**Assignees:** @kev007 and @ChrizZz110 (@IIDP/Front-End)
**Deadline:** Meeting 11.05.2016 @ 13:00
### Details:
1. Fix remaining from last ticket
2. Fix marker population bug
3. Connect the GUI to the REST service
##### Optional UI:
1. [Pagination ](https://angular-ui.github.io/bootstrap/#/pagination)for tweets list
2. Follow responsive design approach. Use [Angular UI](https://angular-ui.github.io/)/Bootstrap and [Angular Layout](http://angular-ui.github.io/ui-layout/)

**Comment by ChrizZz110** [comment]
My changes for the list search are made. 
@kev007 If you are ready, merge it :)
