### ISSUE TITLE
Stream: separation of concerns

### ISSUE THREAD

**Issue by martingrimmer** [IIDP/OSTMap#31]
### Problem

currently the stream does weird stuff 
- one key class for different key types
- one sink for different tables and schemata
### Goal

use separation of concerns (see: https://en.wikipedia.org/wiki/Separation_of_concerns)
- see both images:
  - the first represents the current stream processing
  - the second is the goal
  - details in the meeting
### 1:

![folie1](https://cloud.githubusercontent.com/assets/17045229/15010272/71ca21cc-11eb-11e6-8936-2a51b7f515b7.PNG)
### 2:

![folie2](https://cloud.githubusercontent.com/assets/17045229/15010278/74ef906c-11eb-11e6-8953-c0dd9f3298e5.PNG)

**Comment by loewenzahm** [comment]
Done. The moment @CSchott implemented the use of tokenizer from commons library instead of tokenizer's copy (#28) this could be tested again with real data by @martingrimmer .
