### ISSUE TITLE
geo fields from tweets json

### ISSUE THREAD

**Issue by martingrimmer** [IIDP/OSTMap#34]
Please gather information regarding the fields geo, location and coordinates and post them here.

**Comment by kev007** [comment]
# [Tweet Field Guide](https://dev.twitter.com/overview/api/tweets)

## coordinates

Coordinates: Nullable. Represents the geographic location of this Tweet as reported by the user or client application. The inner coordinates array is formatted as geoJSON (longitude first, then latitude).
Example:

```
"coordinates":
{
    "coordinates":
    [
        -75.14310264,
        40.05701649
    ],
    "type":"Point"
}
```

## geo

Object. **### Deprecated ###**. Nullable. Use the “coordinates” field instead. [Discussion](http://groups.google.com/group/twitter-development-talk/browse_thread/thread/9e4ea75178174908)

## place

Places: Nullable. When present, indicates that the tweet is associated (but not necessarily originating from) a Place.
Example:

```
"place":
{
    "attributes":{},
     "bounding_box":
    {
        "coordinates":
        [[
                [-77.119759,38.791645],
                [-76.909393,38.791645],
                [-76.909393,38.995548],
                [-77.119759,38.995548]
        ]],
        "type":"Polygon"
    },
     "country":"United States",
     "country_code":"US",
     "full_name":"Washington, DC",
     "id":"01fbe706f872cb32",
     "name":"Washington",
     "place_type":"city",
     "url": "http://api.twitter.com/1/geo/id/01fbe706f872cb32.json"
}
```

**Comment by martingrimmer** [comment]
- so we use the coordinates field
