### ISSUE TITLE
Backend: Sliding histogram of incoming tweets

### ISSUE THREAD

**Issue by merando** [IIDP/OSTMap#40]
### Story

We want to see the frequency of tweets by language over time. To do so we have to prepare a proper table.
### Steps
1. Create and [document ](https://github.com/IIDP/OSTMap/wiki/Accumulo-schema) a new Accumulo table called: "TweetFrequency"
   - row key as String of format --> YYYYMMDDhhmm
   - family --> the language tag of the tweet (see JSON tag "lang")
   - qualifier --> [empty]
   - value --> number of tweets of this language
2. Extend the stream ingest after the "DateExtraction" using the flink window functionioanlity to create one minute buckets which count the number of tweets per language.
3. Write the results of the window function to the created accumulo table.

**Comment by loewenzahm** [comment]
@merando: you want me to write number of tweets of this language **per window** instead of all time sum don't you?

I understood it this way:

```
              201605051430    en    -     3                    
```

now there are 5 new incoming english tweets during the next minute so it'll be:  

```
              201605051430    en    -     3       
              201605051431    en    -     5       
```

right?

**Comment by loewenzahm** [comment]
sorry, edited my comment.

**Comment by merando** [comment]
hey @loewenzahm .
you got it totally right.
