### ISSUE TITLE
Frontend: Sliding histogram of incoming tweets

### ISSUE THREAD

**Issue by merando** [IIDP/OSTMap#41]
Depends on #40 .
### Story

Create a REST service and web ui for the sliding histogram data of the "TweetFrequency" table.
### Steps
1. Create a rest service capable of querying data of the "TweetFrequency" by time range (has to be choosen) and language (optional)
2. Create a new tab in the frontend for statistics
3. Use stacked bars to visualize the frequency and language of a minute bucket in the frontend.

**Comment by kev007** [comment]
Location: Analytics Tab
Planned interface:
http://code.shutterstock.com/rickshaw/
https://github.com/shutterstock/rickshaw

**Comment by martingrimmer** [comment]
Data for this is now available in accumulo.
See wiki for detailed table information.

**Comment by martingrimmer** [comment]
rest service done

**Comment by kev007** [comment]
There seems to be lots of gaps in the data!
![tweetfreq](https://cloud.githubusercontent.com/assets/3058438/15593004/9317a772-23a8-11e6-9592-54df56083f3c.PNG)

**Comment by martingrimmer** [comment]
- tweet timestamps are utc we should consider this
- the graph does not change when i start a new request for another time range

**Comment by kev007** [comment]
Done. Any suggestions?
