### ISSUE TITLE
tests for rest_service failing

### ISSUE THREAD

**Issue by HansPog** [IIDP/OSTMap#43]
when running GeoTimePeriodTest I get:

> java.lang.AssertionError: 
> Expected :application/json;charset=UTF-8
> Actual   :text/html;charset=utf-8

did something go wrong with the gradle dependencies during combination of the projects, or is this a problem with your class(es)?

**Comment by ChrizZz110** [comment]
@HansPog Please check out branch #43-tests-rest-service and run the build again. If it works we can merge with master, delete the branch and close the ticket.

**Comment by HansPog** [comment]
still getting:

```
23:44:04.290 [main] DEBUG o.s.boot.test.TestRestTemplate - Created GET request for "http://localhost:8080/api/geotemporalsearch?bbnorth=10.123&bbsouth=-10.456&bbeast=-30.789&bbwest=30.123&tstart=1462020290&tend=1462020291"
23:44:04.294 [main] DEBUG o.s.boot.test.TestRestTemplate - Setting request Accept header to [text/plain, application/json, application/*+json, */*]
23:44:04.303 [main] DEBUG o.s.boot.test.TestRestTemplate - GET request for "http://localhost:8080/api/geotemporalsearch?bbnorth=10.123&bbsouth=-10.456&bbeast=-30.789&bbwest=30.123&tstart=1462020290&tend=1462020291" resulted in 404 (Not Found); invoking error handler
23:44:04.304 [main] DEBUG o.s.boot.test.TestRestTemplate - Reading [java.lang.String] as "text/html;charset=utf-8" using [org.springframework.http.converter.StringHttpMessageConverter@7364985f]

java.lang.AssertionError: 
Expected :application/json;charset=UTF-8
Actual   :text/html;charset=utf-8
```

is there anything to do before your tests can work (server starting, ...)?
if so, please rewrite your tests, so that they configure everything on their own. 
tests should be able to run automatically (f.eg. if you run "gradle build" all tests in the project have to succeed)

**Comment by ChrizZz110** [comment]
@HansPog Please give it another try.

**Comment by ChrizZz110** [comment]
Merged to master. @HansPog Please try the build at the master branch.
