### ISSUE TITLE
Rest service for token tweet search

### ISSUE THREAD

**Issue by martingrimmer** [IIDP/OSTMap#5]
### Goal:

Develop a rest service the OSTMap UI can query against for tweet search. 
- use spring boot
- path: `/tokensearch`
- parameter: e.g. `field=user&field=text&token=twitter`
  - `field` the json fields to seach
  - `token` the token/word to search for
- returns matching json string, one per line
### Details:

When called the service builds up a connection to accumulo, queries the TermIndex table and than the RawTwitterData with a BatchScanner.

**Comment by ChrizZz110** [comment]
Closed. Next steps for the webservice in a seperate ticket.
