### ISSUE TITLE
GUI bugfixes and feature catchup

### ISSUE THREAD

**Issue by kev007** [IIDP/OSTMap#50]
**Task:** Fix those bugs!
**Assignees:** @kev007 and @ChrizZz110 (@IIDP/Front-End)
**Deadline:** TODAY! (11.05.2016 @ 23:59)

Existing bugs:
1. URL encoding (fixed)
2. Incorrect bounding box coordinates (fixed)
3. Fix tend and tstart (fixed)
4. Remove test marker (done)

**Comment by ChrizZz110** [comment]
use uri /api/testgeo
