### ISSUE TITLE
UI/Webservice Pagination for List of Tweets

### ISSUE THREAD

**Issue by ChrizZz110** [IIDP/OSTMap#56]
# Pagination

Paginate the list of tweets.

A request to /tokensearch could contain two optional query params: 

limit = number > 0

offset = number >= 0

Example: Request to /api/tokensearch?fields=text,user&token=yolo&limit=100&offset=100

means: get all tweets from 100 to 199

**Comment by martingrimmer** [comment]
-> we do this on client side now
