### ISSUE TITLE
tokensearch for #hastag doesn't work

### ISSUE THREAD

**Issue by HansPog** [IIDP/OSTMap#61]
searching for a token beginning with # results in error 400 bad request

**Comment by ChrizZz110** [comment]
Fixed. Worked correctly at UnitTest. 
@martingrimmer Please deploy live to see if its working live.

**Comment by martingrimmer** [comment]
bug is still there

**Comment by ChrizZz110** [comment]
Bug is located at the UI... the # character is not url encoded if the request is send. I'll fix it asap

**Comment by ChrizZz110** [comment]
Added URL encoding in the UI for token search. @martingrimmer Please give it another try. Only the javascript file service.http.js has chaged. If you like : simple exchange it.

**Comment by merando** [comment]
martin deployed the current version but it still didn't work.

Please merge to master if not done already.
