### ISSUE TITLE
GeoTemp commons for key creation

### ISSUE THREAD

**Issue by HansPog** [IIDP/OSTMap#62]
create commons classes for key creation for GeoTempIndex keys
### Details
- use this geohash library: [com.github.davidmoten.geo](https://github.com/davidmoten/geo)
- see [wiki: accumulo tables](https://github.com/IIDP/OSTMap/wiki/Accumulo-schema) for details regarding the table/key structure

**Comment by martingrimmer** [comment]
see [wiki: accumulo tables](https://github.com/IIDP/OSTMap/wiki/Accumulo-schema) for details regarding the table/key structure
