### ISSUE TITLE
GeoTemp commons api

### ISSUE THREAD

**Issue by HansPog** [IIDP/OSTMap#63]
create api for GeoTempSearch in commons
### Details:
- we want an interface: `TweetCallback`
  - with one method: `void process(String json);` which is called from the query class for each result tweet
- we want a class `GeoTemporalTweetQuery`with methods:
  - `setBoundingBox`, `setTimeRange`, `setCallback`, `query`

see [wiki: accumulo tables](https://github.com/IIDP/OSTMap/wiki/Accumulo-schema) for details regarding the table/key structure

**Comment by martingrimmer** [comment]
see [wiki: accumulo tables](https://github.com/IIDP/OSTMap/wiki/Accumulo-schema) for details regarding the table/key structure
