### ISSUE TITLE
Use Extractor for Location Extraction

### ISSUE THREAD

**Issue by CSchott** [IIDP/OSTMap#67]
Currently there are some classes that are parsing the locations by the coordinates field(for example geoTimePeriodController of the restService). These classes should be updated to use the Extractor instead. 
The Unit tests of these classes should be updated as well. 

@ChrizZz110 
@MrBlaTi 
@loewenzahm 

Especally for your current projects this could be interesting.

**Comment by loewenzahm** [comment]
Done in GeoTemporalKey and GeoTemporalKeyTest.

**Comment by MrBlaTi** [comment]
what if the coordinates are located in the "geo" field? as I recall, that was a possibility as well

**Comment by kev007** [comment]
Geo was deprecated by Twitter. See issue [34](https://github.com/IIDP/OSTMap/issues/34#issuecomment-216844254)

**Comment by MrBlaTi** [comment]
Done in areacalc
