### ISSUE TITLE
Rest Service - Top 10 Hashtags 

### ISSUE THREAD

**Issue by ChrizZz110** [IIDP/OSTMap#72]
In addition to the results of tokensearch request, a list with top 10 hashtags should returned if the query parameter "topten" is pesent in the request and has the value true or 1

e.g. `.../api/tokensearch?field=text&token=yolo&topten=true`

the default value of topten is false, so if the parameter isn't set, no hashtags-list will be added and only one element "tweets" is in the retured json object.

The response of an request will look like:

```
{   
"tweets": [ {"created_at": "W...},{"created_at": "W...},...],  

"topten" : [ "#hashtag1","#hashtag2","#hashtag3",....]
}
```

`"#hashtag1"` is the most frequenty hashtag in the result  

...

`"#hashtag10"` is the 10th most frequenty hashtag in the result  

After this is implemented, i'll add it to the wiki in webservice part.

@kev007 you can have a look at the structure above. In future we can think about a list of all tweet_ids to each hashtag to see, in which tweets the hashtag occurs.

**Comment by ChrizZz110** [comment]
@kev007 I added this functionality in branch `iss72-webservice-top-ten-hashtags` . Please checkout that branch, do the neccessary changes in the ui code (add query parameter topten, access tweets for tweet list ...) and merge it to master.

**Comment by martingrimmer** [comment]
todo: merge

**Comment by kev007** [comment]
//TODO: client side filtering when selecting a hashtag

**Comment by kev007** [comment]
Done. Any suggestions?

**Comment by ChrizZz110** [comment]
I'll fix the case sensitive problem

**Comment by ChrizZz110** [comment]
Done and merged into master branch. Please test it on live system after deploy. If it's working, close this ticket and delete Branch `iss72-webservice-top-10-hashtags`
