### ISSUE TITLE
Rest Service - reduce result for GeoTempSearch

### ISSUE THREAD

**Issue by ChrizZz110** [IIDP/OSTMap#74]
At the moment: if /api/geotemporalsearch was requested, the complete tweet with data:
- text, user.name, user.screenname,user.profile_image_url, coordinates, created_at, place.bounding_box.coordinates, id

will be returned.

In future, only data
- coordinates ,place.bounding_box.coordinates und id 

should be returned

**Comment by ChrizZz110** [comment]
@merando: I think @martingrimmer said that this ticket is part of Milestone 3. Can you clear that?

**Comment by martingrimmer** [comment]
moved to MS 3

**Comment by martingrimmer** [comment]
done
