### ISSUE TITLE
helper for Accumulo mini cluster

### ISSUE THREAD

**Issue by martingrimmer** [IIDP/OSTMap#8]
### Goal:

We need a helper class to start and stop an accumulo mini cluster to be used in unit tests.
### Details:

Develop a java class: `AmcHelper` with following methods:
- `public MiniAccumuloCluster startMiniCluster(String tempPath)`
- `public Connector getConnector()`
- `public void stopMiniCluster()`
- this class should be in submodul: commons
- package: org.iidp.ostmap.commons.accumulo

for further details see accumulo documentation: https://accumulo.apache.org/1.7/accumulo_user_manual.html#_mini_accumulo_cluster
### Usage:

This class should be used in JUnit tests. For example in this way:

``` java
import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.ClassRule;
import org.junit.Test;
import org.junit.rules.TemporaryFolder;
// further imports
public class SomeTest {
    @ClassRule
    public static TemporaryFolder tmpDir = new TemporaryFolder();
    public AmcHelper amc = new AmcHelper();

    @BeforeClass
    public static void setUpCluster() throws AccumuloException, AccumuloSecurityException, InterruptedException, IOException {
        amc.startMiniCluster(tmpDir.getRoot().getAbsolutePath());
    }

    @AfterClass
    public static void shutDownCluster() throws IOException, InterruptedException {
        amc.stopMiniCluster();
    }

    @Test
    public void testSomething() {
        Connector connector = amc.getConnector();
        System.out.println("I am connected as: " + connector.whoami());
    }
}
```

**Comment by merando** [comment]
IMO this class should only be accessible in tests.
So the implementation has to reside in src/main/test
