### ISSUE TITLE
REST Service - Convert Tweet ID to String

### ISSUE THREAD

**Issue by kev007** [IIDP/OSTMap#82]
JavaScript number type (double-precision) only has about 15 digits of precision. Javascript rounds any extra digits! Since a Tweet ID has 18 digits, the ID is rounded (very, very bad) 

Example:
id: 732822797798539264
turns to:
id: 732822797798539300

The REST service should use the id_str field or convert the id to a string:
id: "732822797798539264"

...
So much time was wasted debugging this.

I now hate javascript.

**Comment by kev007** [comment]
This is also why some tweets were missing from the map. The chance that tweets had similar IDs was high since IDs are assigned sequentially. Tweets with similar timestamps have similar IDs, therefore collisions occurred when they were rounded.

**Comment by martingrimmer** [comment]
Lets use the `id_str` field. I will change the `ExtractIterator` in this way.

**Comment by martingrimmer** [comment]
ill do it
