### ISSUE TITLE
Upper bound for results in ui/rest

### ISSUE THREAD

**Issue by martingrimmer** [IIDP/OSTMap#85]
### Details
- To prevent the ui and rest server for freezes we should stop iterating the results from accumulo when a defined amount is reached.
- the Rest Service has to count the results
- if a number of (eg) 5000 is reached it should close the Scanner and return the results to the client with the information that there are more.
- this can prevent us from full table Scans and dying rest processes

**Comment by kev007** [comment]
Whoops, that commit was supposed to be referencing ticket #86.

**Comment by martingrimmer** [comment]
wontfix
