### ISSUE TITLE
OSTMap Presentation 

### ISSUE THREAD

**Issue by ChrizZz110** [IIDP/OSTMap#88]
### Create a presentation about OSTMap

Assignees: @CSchott @ChrizZz110 @loewenzahm 
- mgm logo
- description of the topic
- tasks
- How we resolve tickets/do tasks? Weekly Meetings, Ticket-System, ...
- Technologies: Which and for what? Big Data seperate ... 
- show a use case : User over ui request RestService etc.

http://slides.com/chrizzz110/ostmap

**Comment by martingrimmer** [comment]
We need to talk about the presentation. there are some issues...

**Comment by loewenzahm** [comment]
@ChrizZz110 :  I talked to @martingrimmer and improved the presentation as far as possible but there is one thing missing: Due to the impossibility of editing the chart you designed for the concept-slide (you imported it as a picture) I would ask you to change the following things:
- Replace Accumulo DB by the official logo
- Use flink-logo (squirrel) for stream- and batch-processing
- Reduce arrows (one connection from Client to UI, one between flink and accumulo, stream-processing is ok)

**Comment by HansPog** [comment]
atm there are 2 slides with heading "Stream-Processing". should one be "batch"?

**Comment by martingrimmer** [comment]
In my view its ok to show two stream jobs. There is almost no difference between a stream and a batch job with flink.

**Comment by ChrizZz110** [comment]
![image](https://cloud.githubusercontent.com/assets/18614530/15683801/6fa87c5c-2764-11e6-9df7-1ed490639c86.png)
Is that OK ?

**Comment by ChrizZz110** [comment]
@loewenzahm : On Slide "Stream-Processing - Geo Temporaler Index" is written: "Tage seit 1970" -> Is "Tage" correct? Not "seconds" or "miliseconds" ?

**Comment by loewenzahm** [comment]
@ChrizZz110 :  Imho the picture is ok. @martingrimmer what do you think? Did I forget or misunderstand something?
@ChrizZz110 again :  Yes, it's days.

**Comment by martingrimmer** [comment]
- the webservice does not communicate with flink
- it talk to accumulo only

**Comment by martingrimmer** [comment]
We have Batch processes in the backend with flink

**Comment by ChrizZz110** [comment]
![image](https://cloud.githubusercontent.com/assets/18614530/15686501/e520c884-2770-11e6-87b6-3e41c3147df3.png)

**Comment by ChrizZz110** [comment]
Better?

**Comment by martingrimmer** [comment]
- yes
- please add angularJS as frontend technology

**Comment by loewenzahm** [comment]
Added angularJS to the technologies-slide.

**Comment by ChrizZz110** [comment]
Added the new concept to the concept slide. I think the presentation is ready.

**Comment by martingrimmer** [comment]
done and closed
