### ISSUE TITLE
clean up package structure

### ISSUE THREAD

**Issue by merando** [IIDP/OSTMap#9]
The package hierarchy of our project has to be adapted to 

main package: org.iidp.ostmap

Please supervise this issue and check that the process tooks place smoothly.

**Comment by CSchott** [comment]
in main package following structure: 
/
- site 
- commons
- converter
- examples
- stream-ingest
- rest-services

**Comment by merando** [comment]
hey @CSchott . your information refer to issue #14 . An updated project structure is proposed there. 
However, this ticket refers to the package structure.
